### ISSUE TITLE
veil and veil iron conflict

### ISSUE THREAD

**Issue by Vyrshkana** [matt-lowe/Lich#15]
Both veil and veil iron are listed in "uncommon" in gameobj-data.xml.  Veil iron is the material; veil by itself creates a conflict with the clothing item veil and otherwise is not used to any effect that I am able to discover.

Can veil please be removed from the standard gameobj-data.xml file?

**Comment by sandersch** [comment]
I see what you are saying. I agree that only `veil iron` should be in the uncommon section. I will add a test for this and update the gameobj-data.xml soon.

**Comment by mrhoribu** [comment]
This should be good to close as it should now be resolved in the most current gameobj-data.xml that is on the in-game repository.
