### ISSUE TITLE
Computer Date Issue

### ISSUE THREAD

**Issue by kaltair1** [matt-lowe/Lich#63]
Getting the following message on login:

--- warning: Your computer thinks the date is 06-08-2024.  If this is the
---          correct date, you need an updated version of this script.  If 
---          this is not the correct date, you need to change it.  In either
---          case, this date makes the SSL certificate in this script invalid
---          and will prevent the script from connecting to the server.

That is the correct date ... not sure how to update the script in order to get a valid SSL cert. Thanks in advance.

**Comment by mrhoribu** [comment]
> Getting the following message on login:
> 
> --- warning: Your computer thinks the date is 06-08-2024. If this is the --- correct date, you need an updated version of this script. If --- this is not the correct date, you need to change it. In either --- case, this date makes the SSL certificate in this script invalid --- and will prevent the script from connecting to the server.
> 
> That is the correct date ... not sure how to update the script in order to get a valid SSL cert. Thanks in advance.

@kaltair1 If you’re on Lich5 you just do this:
;lich5-update --script=repository.lic

Then if you need newer version of lnet that works with Ruby3+ and newest Lich5 you’d do this:
;repo download lnet --game=gs

Also for Lich5 and current development of Lich you’d want to look at the following links for help/support
DR - https://github.com/rpherbig/dr-scripts/wiki/First-Time-Setup
GS4 - https://gswiki.play.net/Lich:Software/Installation

For help via discord you can visit the following:
DR - https://discord.gg/cdVHPGQFcQ
GS4 - https://discord.gg/KF9Wr8u

**Comment by kaltair1** [comment]
That worked. Thank you.
